# Generated by Django 3.2.5 on 2021-07-06 17:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeerMasTarde',
            new_name='Cart',
        ),
    ]
