# Generated by Django 3.2.5 on 2021-07-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0005_alter_producto_detalles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=1000)),
                ('nombre', models.CharField(max_length=100)),
                ('domicilio', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('cpostal', models.CharField(max_length=100)),
            ],
        ),
    ]
