# Generated by Django 3.2.5 on 2021-07-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0007_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seccion',
            old_name='nomCateg',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='seccion',
            name='slug',
            field=models.SlugField(default='1', unique=True),
            preserve_default=False,
        ),
    ]
