# Generated by Django 3.2.5 on 2021-07-07 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0008_auto_20210707_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='seccion',
            old_name='nombre',
            new_name='nomCateg',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='slug',
        ),
        migrations.AlterField(
            model_name='producto',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificacion_seccion', to='Tienda.categoria'),
        ),
    ]
