# Generated by Django 3.2.5 on 2021-07-07 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0009_auto_20210707_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificacion_seccion', to='Tienda.seccion'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
